input.onButtonPressed(Button.A, function () {
    music.playMelody("C5 - - - - - - - ", 92)
    basic.clearScreen()
    basic.showString("Video 2")
    basic.showString("MOO event(under December)")
    basic.showString("Game 1")
    basic.showString("Story 1")
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("C5 - - - - - - - ", 92)
    basic.clearScreen()
    basic.showString("www.moo-com.glitch.me")
})
music.playMelody("C5 G C G E A F G ", 92)
basic.showString("Welcome to MOO System of micro:bit")
music.playMelody("C5 G C G E A F G ", 92)
basic.clearScreen()
basic.showString("What do you want to do with this system?")
basic.showString("A. What did MOO do in this year?")
basic.showString("B. MOO website")
